### ISSUE TITLE
MatchError when there's a path with `=` in the name

### ISSUE THREAD

**Issue by rhnonose** [falood/file_system#48]
OS: `macOS High Sierra 10.13.1`
Elixir version: `1.6.2`
Erlang/OTP version: `20`

When there's a dir/filename with the `=` character in the name, it throws the following error:

```
[error] GenServer #PID<0.480.0> terminating
** (MatchError) no match of right hand side value: ["20888710", "0x00020100", "[created]", "/tmp/test", "2"]
    (file_system) lib/file_system/backends/fs_mac.ex:174: FileSystem.Backends.FSMac.parse_line/1
    (file_system) lib/file_system/backends/fs_mac.ex:153: FileSystem.Backends.FSMac.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {#Port<0.23416>, {:data, {:eol, '20888710\t0x00020100=[created]\t/Users/rhnonose/dev/emcasa/hammock/page=2'}}}
State: %{port: #Port<0.23416>, worker_pid: #PID<0.479.0>}
```

To reproduce: create a directory with `=` in the name while watching for changes.

**Comment by falood** [comment]
merged and released v0.2.5 ❤️
